PACKAGING_MATERIALS = [
    {
        "material_id": "MET_PET_PE",
        "name": "Metallized PET / Polyethylene Laminate",
        "category": "High Barrier Foil Laminate",
        "typical_thickness_um": 70,
        "otr": 1.5,          # cc/m²/day
        "wvtr": 1.0,         # g/m²/day
        "breathable": False,
        "map_suitable": True,
        "freezer_grade": False,
        "sustainability_score": 3,
        "cost_index": 4,
        "best_for": "Fried snacks, potato chips, nuts, milk powder, roasted items"
    },
    {
        "material_id": "BOPP_25u",
        "name": "Biaxially Oriented Polypropylene (BOPP)",
        "category": "Moisture Barrier Film",
        "typical_thickness_um": 25,
        "otr": 1200.0,
        "wvtr": 4.5,
        "breathable": False,
        "map_suitable": False,
        "freezer_grade": False,
        "sustainability_score": 6,
        "cost_index": 2,
        "best_for": "Biscuits, bakery products, pasta, dry confectionery"
    },
    {
        "material_id": "PERF_LDPE_35u",
        "name": "Micro-Perforated LDPE Breathable Film",
        "category": "Breathable Produce Film",
        "typical_thickness_um": 35,
        "otr": 4500.0,
        "wvtr": 18.0,
        "breathable": True,
        "map_suitable": True,
        "freezer_grade": False,
        "sustainability_score": 5,
        "cost_index": 2,
        "best_for": "Fresh fruits, vegetables, salad greens, cut produce"
    },
    {
        "material_id": "LDPE_50u",
        "name": "Standard Low-Density Polyethylene (LDPE)",
        "category": "General Purpose Flexible Poly",
        "typical_thickness_um": 50,
        "otr": 2800.0,
        "wvtr": 14.0,
        "breathable": True,
        "map_suitable": True,
        "freezer_grade": True,
        "sustainability_score": 5,
        "cost_index": 1,
        "best_for": "Short shelf-life groceries, bread, frozen vegetables"
    },
    {
        "material_id": "PA_PE_VACUUM",
        "name": "Polyamide (Nylon) / PE Multi-layer Vacuum Film",
        "category": "Puncture-Resistant Vacuum Barrier",
        "typical_thickness_um": 90,
        "otr": 25.0,
        "wvtr": 3.5,
        "breathable": False,
        "map_suitable": True,
        "freezer_grade": True,
        "sustainability_score": 4,
        "cost_index": 4,
        "best_for": "Fresh paneer, cheese blocks, processed meat, frozen fish"
    },
    {
        "material_id": "RETORT_POUCH",
        "name": "Multi-tier Aluminum Retort Stand-up Pouch",
        "category": "Ultra High Barrier Sterilizable",
        "typical_thickness_um": 110,
        "otr": 0.1,
        "wvtr": 0.1,
        "breathable": False,
        "map_suitable": False,
        "freezer_grade": False,
        "sustainability_score": 2,
        "cost_index": 5,
        "best_for": "Ready-to-eat gravies, cooked curries, baby purees, wet pastes"
    },
    {
        "material_id": "PLA_BIO_40u",
        "name": "Poly-Lactic Acid (PLA) Compostable Bio-film",
        "category": "Eco-friendly Biodegradable",
        "typical_thickness_um": 40,
        "otr": 550.0,
        "wvtr": 38.0,
        "breathable": True,
        "map_suitable": True,
        "freezer_grade": False,
        "sustainability_score": 9,
        "cost_index": 4,
        "best_for": "Organic dry goods, fresh berries, eco-conscious retail fruits"
    },
    {
        "material_id": "HDPE_CANISTER",
        "name": "High-Density Polyethylene (HDPE) Rigid/Semi-rigid",
        "category": "Rigid Barrier Container",
        "typical_thickness_um": 250,
        "otr": 600.0,
        "wvtr": 2.0,
        "breathable": False,
        "map_suitable": False,
        "freezer_grade": True,
        "sustainability_score": 7,
        "cost_index": 3,
        "best_for": "Edible oils, ghee, dairy milk, honey, liquid seasonings"
    },
    {
        "material_id": "KRAFT_PE_POUCH",
        "name": "Kraft Paper / Polyethylene Moisture Barrier Pouch",
        "category": "Paper-Plastic Composite",
        "typical_thickness_um": 85,
        "otr": 400.0,
        "wvtr": 5.0,
        "breathable": False,
        "map_suitable": False,
        "freezer_grade": False,
        "sustainability_score": 8,
        "cost_index": 3,
        "best_for": "Tea leaves, roasted coffee beans, whole spices, grain pulses"
    }
]
